from sentence_transformers import SentenceTransformer, util

INTENCIONES = {
    "MUSICA": [
        "pon música",
        "dale música",
        "quiero escuchar una canción",
        "pon rock",
        "pon reguetón",
        "pon salsa",
        "pon música de fondo",
        "quiero oír música",
        "pon algo bueno",
        "échate un tema",
        "pónme una rola",
        "quieres poner música",
        "pon los Beatles",
        "pon una rola",
        "ponle música",
        "échate un rolón",
        "quiero oír algo tranquilo",
        "pon algo de pop",
        "pon música alegre",
        "quiero escuchar algo",
        "pon lo que sea",
        "pon música para bailar",
        "pon algo de moda",
        "quiero oír mis canciones",
        "pon música relajante",
        "pon música para entrenar",
        "pon música para dormir",
        "pon algo de banda",
        "échate un poco de música",
        "quieres poner algo",
        "pon sonido ambiente",
        "dale play a la música",
        "reproduce música",
        "pon algo suave",
        "quiero oír música para concentrarme",
        "pon música en ingles",
        "pon música en español",
        "pon algo de heavy metal",
        "pon electrónica",
        "quiero escuchar el playlist",
        "pon mi lista de reproducción",
        "pon canciones que me gustan",
        "quiero escuchar mis canciones favoritas",
        "dale play",
        "pon algo bueno para escuchar",
        "quiero oír una canción que me alegre",
        "pon música que me guste",
        "reproduce mi playlist de Spotify",
        "pon la playlist de rock",
        "pon música de los 80",
        "pon música de los 90",
        "quiero escuchar música nueva",
        "pon los éxitos del momento",
        "pon canciones en español",
        "pon música de los 2000",
        "pon algo tranqui",
        "pon música que me motive",
        "búscame una canción",
        "reproduce mi lista de reproducción favorita",
        "pon música que me haga sentir bien",
        "quiero que suene algo",
        "pon algo que no sea tan pesado",
        "pon un poco de todo",
        "quiero que pongas música",
        "pon un temita",
        "pon música para la fiesta",
        "pon algo de jazz",
        "pon algo de blues",
        "pon música instrumental",
        "pon clásica",
        "pon algo de música electrónica",
        "quiero escuchar un poco de todo",
        "pon música pop",
        "pon música de rock en español",
        "pon canciones que conozco",
        "pon mi música",
        "quiero oír el playlist que hice",
        "pon música para estudiar",
        "pon música de fondo para trabajar",
        "quiero oír algo que me guste",
        "pon algo de reggae",
        "pon algo de hip hop",
        "pon algo de rap",
        "pon algo de cumbia",
        "pon algo de bachata",
        "pon algo de merengue",
        "pon algo de tango",
        "pon algo de flamenco",
        "pon algo de música latina",
        "échate un playlist",
        "pónme algo que no conozca",
        "quiero escuchar música que me sorprenda",
        "pon música que no haya escuchado antes",
        "quiero oír música nueva para mí",
        "dale play a mi música",
        "quiero escuchar algo de R&B",
        "pon un poco de soul",
        "quiero escuchar funk",
        "pon algo de música disco",
        "pon algo de música clásica",
        "quiero oír música para relajarme",
        "pon música para meditar",
        "reproduce algo suave",
        "pon música tranquila",
        "quiero escuchar algo movido",
        "pon música que suba el ánimo",
        "pon algo para alegrarme el día",
        "quiero escuchar canciones que me hagan cantar",
        "pon algo para cantar",
        "pon música para karaoke",
        "quiero oír canciones para bailar",
        "pon un poco de acción musical",
        "pon música que me ponga de buenas",
        "quiero escuchar algo que me haga feliz",
        "pon la música que te pedí",
        "reproduce mi playlist de siempre",
        "pon mis canciones guardadas",
    ],
    "CORREO": [
        "envía un correo",
        "manda un email",
        "escribe un mensaje",
        "quiero enviar un correo",
        "mándale un mail a",
        "redacta un correo",
        "envía un email",
        "échale un mailazo",
        "manda un correo electrónico",
        "escribe un email",
        "mándale un meil",
        "quiero mandar un correo",
        "envía un correo a Juan",
        "escribe un email urgente",
        "manda un mail con copia",
        "envía un mensaje de correo",
        "redacta un email para",
        "quiero escribir un correo",
        "manda un correo formal",
        "envía un mail adjuntando archivo",
        "prepara un correo",
        "mándale un mail a mi jefe",
        "escribe una carta por email",
        "envía una respuesta por correo",
        "contesta ese correo",
        "reenvía el correo",
        "manda un correo a varios destinatarios",
        "envía un email con asunto",
        "redacta una propuesta por correo",
        "mándale un mensaje por email",
        "escribe un correo de presentación",
        "envía un mail de agradecimiento",
        "prepara un correo de bienvenida",
        "redacta una notificación por correo",
        "envía un recordatorio por email",
        "manda un correo de seguimiento",
        "envía una invitación por correo",
        "redacta un mensaje de correo urgente",
    ],
    "CALENDARIO": [
        "qué eventos tengo hoy",
        "muéstrame mi calendario",
        "qué hay en mi agenda",
        "agenda una reunión",
        "crea un evento",
        "recuérdame qué tengo mañana",
        "mis citas de hoy",
        "qué reuniones tengo",
        "programa una cita",
        "agenda una llamada",
        "qué tengo mañana en el calendario",
        "muéstrame los eventos de la semana",
        "agrega un evento a mi calendario",
        "qué compromisos tengo",
        "cita pendiente en mi agenda",
        "crea un recordatorio",
        "qué actividades tengo hoy",
        "enséñame mi agenda",
        "revisa mi calendario",
        "qué hay programado para mañana",
        "qué tengo esta semana",
        "quiero agendar algo",
        "pon una reunión en mi calendario",
        "reserva una cita",
        "agenda una videollamada",
        "programa un evento para el viernes",
        "crea un evento de cumpleaños",
        "recuérdame que tengo una cita",
        "qué tengo el lunes",
        "qué tengo el fin de semana",
        "muéstrame los eventos de mañana",
        "agenda una reunión para mañana",
        "programa una cita médica",
        "qué reuniones tengo pendientes",
        "pon en mi agenda una llamada",
        "quiero ver mi calendario",
        "abre mi calendario",
        "qué tengo agendado para hoy",
        "qué citas tengo hoy",
        "dime mis eventos del día",
        "qué planes tengo para mañana",
    ],
    "TELEGRAM": [
        "manda un mensaje por telegram",
        "dile a Juan que",
        "envía un Telegram",
        "mándale un mensaje",
        "manda un wasap",
        "dile por wasap",
        "envía un guasap",
        "chatea con",
        "mándale un msj",
        "dile que voy tarde",
        "manda un wsp",
        "envía un mensaje de texto",
        "mándale un WhatsApp",
        "dile por mensaje",
        "mándale un texto a",
        "comunícale a",
        "notifícale a",
        "avísale a",
        "mándale una nota de voz",
        "envía un audio por telegram",
        "dile algo a",
        "pásale un mensaje a",
        "dile que ya llego",
        "avísale que voy en camino",
        "mándale un saludo",
        "dile que lo espero",
        "envía una foto por telegram",
        "mándale un voz por wasap",
        "habla con",
        "ponte en contacto con",
        "mándale un mensaje urgente",
        "dile que me llame",
        "avísale del cambio de plan",
        "mándale la dirección",
        "dile dónde nos vemos",
        "confírmale la cita",
        "pregúntale si viene",
        "recuérdale lo de mañana",
        "dile que lo esperamos",
        "mándale un emoji",
        "dile que estamos aquí",
    ],
    "NAVEGADOR": [
        "abre el navegador",
        "busca en internet",
        "googlea",
        "abre una página",
        "navega a",
        "busca en Google",
        "guglea",
        "búscalo en internet",
        "consulta en Google",
        "abre Chrome",
        "quiero buscar algo",
        "investiga sobre",
        "búscame información de",
        "abre el buscador",
        "entra a esta página",
        "quiero que busques algo en internet",
        "averigua en internet",
        "consulta en la web",
        "búscame en Google",
        "ve a la página de",
        "abre una pestaña",
        "investiga en la web",
        "busca en la red",
        "navega hasta",
        "quiero abrir el explorador",
        "pon el navegador",
        "búscame datos de",
        "quiero que investigues",
        "abre el buscador web",
        "mira en internet",
        "consulta en línea",
        "busca información sobre",
        "quiero que me busques",
        "haz una búsqueda en Google",
        "ve a Google y busca",
        "abre la página de Wikipedia",
        "búscalo en la red",
        "consulta en el navegador",
        "abre el explorador web",
        "búscame el significado de",
        "abre el navegador de internet",
        "búscalo en línea",
        "búscalo en el navegador",
        "quiero que abras Google",
        "investiga un tema en internet",
        "ponte a buscar en internet",
        "mira si encuentras información de",
    ],
    "PAUSA": [
        "pausa la música",
        "para la música",
        "pausa",
        "silencio",
        "detente",
        "pausa el audio",
        "pon en pausa",
        "quiero pausar",
        "para un momento",
        "espera",
        "pausa la canción",
        "ponle pausa",
        "para la canción",
        "detén el audio",
    ],
    "REANUDAR": [
        "reanuda la música",
        "continúa la música",
        "sigue la música",
        "reanuda",
        "continúa",
        "sigue",
        "reanuda el audio",
        "continúa el audio",
        "vuelve a sonar",
        "quita la pausa",
        "sigue con la música",
        "sigue reproduciendo",
        "otra vez",
    ],
    "SIGUIENTE": [
        "siguiente canción",
        "pasa a la siguiente",
        "siguiente",
        "adelante",
        "salta esta canción",
        "siguiente tema",
        "siguiente pista",
        "saltar",
        "skip",
        "avanza",
        "la siguiente",
        "dale a siguiente",
        "cambia a la siguiente",
    ],
    "ANTERIOR": [
        "canción anterior",
        "vuelve a la anterior",
        "anterior",
        "atrás",
        "regresa",
        "la anterior",
        "pon la de antes",
        "devuélvete",
        "retrocede",
        "canción previa",
        "la que estaba antes",
        "vuelve atrás",
        "regresa a la canción anterior",
    ],
    "VOLUMEN": [
        "sube el volumen",
        "baja el volumen",
        "más alto",
        "más bajo",
        "súbele",
        "bájale",
        "volumen al máximo",
        "volumen al mínimo",
        "ponlo más fuerte",
        "ponlo más bajo",
        "sube volumen",
        "baja volumen",
        "aumenta el volumen",
        "disminuye el volumen",
        "súbele al volumen",
        "bájale al volumen",
        "volumen 50",
        "volumen al 50",
        "más fuerte",
        "más flojo",
        "pon volumen",
        "sube el sonido",
        "baja el sonido",
        "volumen al 30",
        "sube un poco",
        "baja un poco",
        "ponlo más alto por favor",
        "bájale un poco",
        "súbele un poco al volumen",
        "volumen al cien",
        "volumen a tope",
        "al máximo",
        "al mínimo",
        "quiero más volumen",
        "menos volumen",
        "sube el audio",
        "baja el audio",
        "pon el volumen al 70",
        "sube el volumen al 80",
        "baja el volumen al 20",
        "pon el volumen al 30",
        "sube el volumen al 90",
        "baja el volumen al 10",
        "pon el volumen al 100",
        "sube el volumen al 60",
        "baja el volumen al 40",
    ],
    "HORA": [
        "qué hora es",
        "dime la hora",
        "dame la hora",
        "qué hora tengo",
        "qué horas son",
        "me puedes decir la hora",
        "me das la hora",
        "dime qué hora es",
        "hora actual",
        "qué hora marca",
        "dime qué hora tengo",
        "la hora por favor",
        "sabes qué hora es",
        "dime la hora exacta",
    ],
}


class Clasificador:
    def __init__(self):
        self.intenciones = INTENCIONES
        self.modelo = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
        self.vectores = {
            k: self.modelo.encode(v, convert_to_tensor=True)
            for k, v in self.intenciones.items()
        }

    def clasificar(self, texto, umbral=0.87, margen_min=0.03):
        vector = self.modelo.encode(texto, convert_to_tensor=True)
        scores = {}
        for intent, vecs in self.vectores.items():
            scores[intent] = util.cos_sim(vector, vecs).max().item()
        mejor = max(scores, key=scores.get)
        mejor_score = scores[mejor]
        segundo_score = sorted(scores.values(), reverse=True)[1]
        margen = mejor_score - segundo_score
        if mejor_score >= umbral and margen >= margen_min:
            return (mejor, mejor_score)
        return ("NO_RECONOCIDO", mejor_score)
