[project]
name = "yartis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ctranslate2>=4.7.2",
    "fastapi>=0.136.3",
    "faster-whisper>=1.2.1",
    "noisereduce>=3.0.3",
    "ntplib>=0.4.0",
    "numpy>=2.4.6",
    "onnxruntime>=1.26.0",
    "openwakeword>=0.4.0",
    "piper-tts>=1.3.0",
    "psutil>=6.0.0",
    "pywin32>=308",
    "pyttsx3>=2.98",
    "sentence-transformers==2.7.0",
    "sounddevice>=0.5.5",
    "soundfile>=0.14.0",
    "spacy>=3.8.14",
    "tiktoken>=0.9.0",
    "torch>=2.12.0",
    "uvicorn>=0.48.0",
    "websockets>=16.0",
    "yt-dlp>=2026.6.9",
    "speechbrain>=1.1.1",
    "librosa>=1.0.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
